export const categorias = [
  "ODS 1 - Erradicação da Pobreza",
  "ODS 2 - Fome Zero e Agricultura Sustentável",
  "ODS 3 - Saúde e Bem-estar",
  "ODS 4 - Educação de Qualidade",
  "ODS 5 - Igualdade de Gênero",
  "ODS 6 - Água Potável e Saneamento",
  "ODS 7 - Energia Acessível e Limpa",
  "ODS 8 - Trabalho Decente e Crescimento Econômico",
  "ODS 9 - Indústria, Inovação e Infraestrutura",
  "ODS 10 - Redução das Desigualdades",
  "ODS 11 - Cidades e Comunidades Sustentáveis",
  "ODS 12 - Consumo e Produção Responsáveis",
  "ODS 13 - Ação Contra a Mudança Global do Clima",
  "ODS 14 - Vida na Água",
  "ODS 15 - Vida Terrestre",
  "ODS 16 - Paz, Justiça e Instituições Eficazes",
  "ODS 17 - Parcerias e Meios de Implementação",
  "ODS 18 - Igualdade Étnico/Racial",
];

export const odsRelacionadas: { [key: string]: string[] } = {
  "ODS 1 - Erradicação da Pobreza": [
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 2 - Fome Zero e Agricultura Sustentável": [
    "ODS 1",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 3 - Saúde e Bem-estar": [
    "ODS 1",
    "ODS 2",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 4 - Educação de Qualidade": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 5 - Igualdade de Gênero": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 6 - Água Potável e Saneamento": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 7 - Energia Acessível e Limpa": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 8 - Trabalho Decente e Crescimento Econômico": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 9 - Indústria, Inovação e Infraestrutura": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 10 - Redução das Desigualdades": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 11 - Cidades e Comunidades Sustentáveis": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 12 - Consumo e Produção Responsáveis": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 13 - Ação Contra a Mudança Global do Clima": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 14 - Vida na Água": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 15",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 15 - Vida Terrestre": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 16",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 16 - Paz, Justiça e Instituições Eficazes": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 17",
    "ODS 18",
  ],
  "ODS 17 - Parcerias e Meios de Implementação": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 18",
  ],
  "ODS 18 - Igualdade Étnico/Racial": [
    "ODS 1",
    "ODS 2",
    "ODS 3",
    "ODS 4",
    "ODS 5",
    "ODS 6 ",
    "ODS 7",
    "ODS 8",
    "ODS 9",
    "ODS 10",
    "ODS 11",
    "ODS 12",
    "ODS 13",
    "ODS 14",
    "ODS 15",
    "ODS 16",
    "ODS 17",
  ],
};

export const cidadesRJ = [
  "Angra dos Reis",
  "Aperibé",
  "Araruama",
  "Areal",
  "Armação dos Búzios",
  "Arraial do Cabo",
  "Barra do Piraí",
  "Barra Mansa",
  "Belford Roxo",
  "Bom Jardim",
  "Bom Jesus do Itabapoana",
  "Cabo Frio",
  "Cachoeiras de Macacu",
  "Cambuci",
  "Campos dos Goytacazes",
  "Cantagalo",
  "Carapebus",
  "Cardoso Moreira",
  "Carmo",
  "Casimiro de Abreu",
  "Comendador Levy Gasparian",
  "Conceição de Macabu",
  "Cordeiro",
  "Duas Barras",
  "Duque de Caxias",
  "Engenheiro Paulo de Frontin",
  "Guapimirim",
  "Iguaba Grande",
  "Itaboraí",
  "Itaguaí",
  "Italva",
  "Itaocara",
  "Itaperuna",
  "Itatiaia",
  "Japeri",
  "Laje do Muriaé",
  "Macaé",
  "Macuco",
  "Magé",
  "Mangaratiba",
  "Maricá",
  "Mendes",
  "Mesquita",
  "Miguel Pereira",
  "Miracema",
  "Natividade",
  "Nilópolis",
  "Niterói",
  "Nova Friburgo",
  "Nova Iguaçu",
  "Paracambi",
  "Paraíba do Sul",
  "Paraty",
  "Paty do Alferes",
  "Petrópolis",
  "Pinheiral",
  "Piraí",
  "Porciúncula",
  "Porto Real",
  "Quatis",
  "Queimados",
  "Quissamã",
  "Resende",
  "Rio Bonito",
  "Rio Claro",
  "Rio das Flores",
  "Rio das Ostras",
  "Rio de Janeiro",
  "Santo Antônio de Pádua",
  "Santa Maria Madalena",
  "São Fidélis",
  "São Francisco de Itabapoana",
  "São Gonçalo",
  "São João da Barra",
  "São João de Meriti",
  "São José de Ubá",
  "São José do Vale do Rio Preto",
  "São Pedro da Aldeia",
  "São Sebastião do Alto",
  "Sapucaia",
  "Saquarema",
  "Seropédica",
  "Silva Jardim",
  "Sumidouro",
  "Tanguá",
  "Teresópolis",
  "Trajano de Moraes",
  "Três Rios",
  "Valença",
  "Varre-Sai",
  "Vassouras",
  "Volta Redonda",
];

export const ApoioPlanejamento = [
  {
    label: "Facilitar o acompanhamento das metas ODS",
    value: "Facilitar o acompanhamento das metas ODS",
  },
  {
    label: "Integrar projetos e políticas públicas",
    value: "Integrar projetos e políticas públicas",
  },
  {
    label: "Promover transparência e engajamento social",
    value: "Promover transparência e engajamento social",
  },
  {
    label: "Apoiar a tomada de decisão baseada em dados",
    value: "Apoiar a tomada de decisão baseada em dados",
  },
  { label: "Outro", value: "Outro" },
];

export const campoLabels: { [key: string]: string } = {
  prefeitura: "Nome da Prefeitura",
  secretaria: "Nome da Secretaria",
  responsavelProjeto: "Responsável pelo Projeto",
  nomeProjeto: "Nome do Projeto",
  ods: "ODS principal do Projeto",
  linkProjeto: "Link do Projeto",
  venceuPspe: "Prêmio Sebrae",
  odsRelacionadas: "ODS Relacionadas",
  apoio_planejamento: "Apoio ao Planejamento",
  apoio_planejamento_outro: "Justificativa 'Outro'",
  escala: "Avaliação de Impacto (Escala)",
  emailContato: "E-mail de Contato",
  descricaoDiferencial: "Briefing do Projeto",
  descricao: "Descrição detalhada",
  confirmacao: "Caixa de Confirmação",
  projetoId: "ID do Projeto",
  motivo: "Motivo da exclusão",
};

export const quillModules = {
  toolbar: [
    [{ header: [1, 2, 3, false] }],
    ["bold", "italic", "underline", "strike"],
    [{ list: "ordered" }, { list: "bullet" }],
    [{ align: [] }],
    ["link"],
    ["clean"],
  ],
};

export const MAX_QUILL_LENGTH = 5000;
